### ISSUE TITLE
Same public key in multiple domU.keys only matches first domU

### ISSUE THREAD

**Issue by mrngm** [bwesterb/xennigan#1]
For example, `alex.hostname.tld.keys` has (at least) one public key in common with `beer.hostname.tld.keys`. Trying to login to xennigan-shell automatically matches the first domU in `/var/lib/xennigan/.ssh/authorized_keys`.

I do not yet see a relevant use case (in principle only one distinct set of public keys should need SSH access to xennigan-shell), but would it be possible to have the user choose between all the machines he can access using his public key(s)?

**Comment by bwesterb** [comment]
I'll add a warning if the same key occurs twice.  I'm a bit torn about adding support for two domus on th same key, as its use is probably rare and it complicates the suid  xen-shell.

**Comment by mrngm** [comment]
That would be fine as well.
