### ISSUE TITLE
xennigan fails to "destroy" (and create) unresponsive vm

### ISSUE THREAD

**Issue by Roflincopter** [bwesterb/xennigan#2]
My Vps was unresponsive, When accessing it with xennigan I was unable to get a console, and a reboot did nothing within a minute. After issuing a "destroy" I encountered some errors. Here a log of the situation.

```
hostname> status                                                                         
Name                                        ID   Mem VCPUs  State   Time(s)
hostname                                   206  3072     2 r-----   78479.7

=============================

hostname> destroy
/etc/xen/scripts/xen-hotplug-common.sh: line 31: /var/log/xen/xen-hotplug.log: Permission denied
/etc/xen/scripts/xen-hotplug-common.sh: line 31: /var/log/xen/xen-hotplug.log: Permission denied
/etc/xen/scripts/xen-hotplug-common.sh: line 31: /var/log/xen/xen-hotplug.log: Permission denied
libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/block remove [-1] exited with error status 1
libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/block remove [-1] exited with error status 1
libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: /etc/xen/scripts/vif-route offline [-1] exited with error status 1

hostname> status
hostname is an invalid domain identifier (rc=-6)
xl exited with code 2

=============================

hostname> create
Parsing config from /etc/xen/hostname.cfg
libxl: error: libxl_bootloader.c:628:bootloader_finished: bootloader failed - consult logfile /var/log/xen/bootloader.207.log
libxl: error: libxl_exec.c:118:libxl_report_child_exitstatus: bootloader [-1] exited with error status 1
libxl: error: libxl_create.c:1022:domcreate_rebuild_done: cannot (re-)build domain: -3
xl exited with code 3

hostname> status
hostname is an invalid domain identifier (rc=-6)
xl exited with code 2
```

**Comment by bwesterb** [comment]
Thanks for reporting!   Do the corresponding xl commands also fail?  What's in the log file?

**Comment by mrngm** [comment]
On dom0, `# xl create domU.cfg` worked as expected. On line 31 in `/etc/xen/scripts/xen-hotplug-common.sh`:

```
exec 2>>/var/log/xen/xen-hotplug.log
```

Permissions:

```
# ls -l xen-hotplug.log
-rw-r--r-- 1 root adm 0 Jan 26 20:48 xen-hotplug.log
```

so this works as expected with regards to the permissions of the xennigan user.

```
# cat bootloader.207.log                                                                                                             Traceback (most recent call last):
  File "/usr/lib/xen-4.4/bin/pygrub", line 839, in <module>
    raise RuntimeError, "Unable to find partition containing kernel"
RuntimeError: Unable to find partition containing kernel
```

is perhaps also due to insufficient permissions?

**Comment by bwesterb** [comment]
Is xennigan-shell setuid?  Is apparmor or something similar active?

**Comment by mrngm** [comment]
I assumed you meant `xennigan-shell` instead of `xen-shell`:

```
/usr/local/bin # ls -hl
-rwsr-xr-- 1 root xennigan 549K Mar 27 03:04 xennigan-shell
```

AppArmor is not installed; the dom0 runs nearly-stock Debian Jessie from `debootstrap`, if I remember correctly. @sgielen?

**Comment by sgielen** [comment]
I think it was the Hetzner image, but it should be very close to debian-minimal. Can't find any traces of AppArmor in /sys, lsmod or dmesg, so I'd say that's not active. There's also nothing in dmesg regarding some kind of permission system kicking into action.

My best guess, currently, considering that `xl console` is working but destroy is not, is that some specific tool eventually called by xennigan is reverting its permissions somehow. For example, a shell setting its EUID back to the UID value or something like that. I will try to run some tests tomorrow and see if I can create a minimal test case.

**Comment by bwesterb** [comment]
I'll try to see if I can reproduce it on KN's dom0...
